# Generated by Django 5.0 on 2026-09-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted'), ('WITHDRAWN', 'Withdrawn')], default='SUBMITTED', max_length=10),
        ),
    ]
