# Generated by Django 5.0 on 2026-09-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_education_user_headline_user_links_user_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_visible_to_recruiters',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_education',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_headline',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_links',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_skills',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_work_experience',
            field=models.BooleanField(default=True),
        ),
    ]
