# Generated by Django 5.2.8 on 2026-09-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_location',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_projects',
            field=models.BooleanField(default=True),
        ),
    ]
